# Generated by Django 4.0.4 on 2022-04-24 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordrecovery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordrecovery',
            name='id',
        ),
        migrations.AddField(
            model_name='passwordrecovery',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
