# Generated by Django 4.0.4 on 2022-04-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_passwordrecovery_id_passwordrecovery_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordrecovery',
            old_name='uid',
            new_name='id',
        ),
    ]
